# QuickSetup Ansible Inventory

# For provisioning directly on the VM / local machine
[local]
localhost ansible_connection=local

# For provisioning remote VMs over SSH
[remote_vms]
# my_vm_ip ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa

[all:vars]
ansible_python_interpreter=/usr/bin/python3
