# QuickSetup Ansible Inventory

# For provisioning directly on the VM / local machine
[local]
localhost ansible_connection=local

[desktop]
localhost ansible_connection=local

[offensive_vm]
localhost ansible_connection=local

[all:vars]
ansible_python_interpreter=/usr/bin/python3
