---
- name: QuickSetup - Provision VM Environment
  hosts: all
  become: true
  roles:
    - role: common
    - role: desktop
      when: install_desktop | default(false)
    - role: development
      when: install_development | default(false)
    - role: offensive
      when: install_offensive | default(false)
    - role: shell
      when: install_shell | default(false)
